language: python
python:
- 3.8
services:
- postgresql
install:
- psql -c 'create database django_db owner postgres;' -U postgres
- pip install -r requirements.txt
script:
- python manage.py migrate
deploy:
  provider: heroku
  api_key:
    secure: trqHy5u0rhYvRE+ojsXDUfkANiyNwhaN5X25J3imjTr9lVkruDm8Wbtz0MV1tgSkGnJjle9WXMf31k56MfJ9p4biZjwftGFWCuWg0xesb//0LOy7oG6B1rhHX0XWpd2fDzJwtVDquCoLZBP/4QgPoVkvYHToU1YdKm+kdIrG1sQ7izBO2HXKx361H+VeIHmh3AvSw+ILnmkVvfE5c6Myyh4XgE+9+kE7iZrkRjGjMC+pRJDTSWxvVj9lPX04Xpr1SZ1WT+COGYGLSgz54XkS6mhRKP/EbVwogpzyPQyIyyQJomuWYN1l6IFMVs5Ok7LBpkX44u8yhKLc+3Af16jayUop2DDtw9xa2huOql9+E/7X/xD9dfAdcyI1IiPejbueROa1ri2X81PgbEk/La0h45100uDd6lOGS5GRrjdR+k4LNMKVL4bURknaBWmHjIVSh3hfeqnitUaTYB8duTgvuexRNNtJpu7KYgxv4rsxAfhJasoy1vJmxgs6wageoKh3fAGZHMRzsBgCDsB3y8MAQ3x6aeG1bOxKWQ3eH8QwDZn3B6KIqxdP32ifkOQH+Cn2kqMF3fCsGWhR0ckj8btlrCZDMFy7oYmr43aZS4E+O14A1HMHO8ctUnZtwRW4+SfHUIhydxum4Cp6lGcBh2oiyAVswffO8n3wCX9TsikQ88k=
  app: kr-nikitin
